[[language]]
name = "markdown"
auto-format = true

[language.formatter]
command = "mise"
args = ["exec", "--", "dprint", "fmt", "--stdin", "md"]

[[language]]
name = "json"
auto-format = true

[language.formatter]
command = "mise"
args = ["exec", "--", "dprint", "fmt", "--stdin", "json"]

[[language]]
name = "yaml"
auto-format = true

[language.formatter]
command = "mise"
args = ["exec", "--", "dprint", "fmt", "--stdin", "yaml"]

[[language]]
name = "asm"
scope = "source.asm"
file-types = ["s"]
auto-format = false
comment-token = ";"
indent = { tab-width = 4, unit = "    " }
